// Generated by gencpp from file osm2rviz/Guide_line.msg
// DO NOT EDIT!


#ifndef OSM2RVIZ_MESSAGE_GUIDE_LINE_H
#define OSM2RVIZ_MESSAGE_GUIDE_LINE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace osm2rviz
{
template <class ContainerAllocator>
struct Guide_line_
{
  typedef Guide_line_<ContainerAllocator> Type;

  Guide_line_()
    : x()
    , y()
    , heading()  {
    }
  Guide_line_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , heading(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_type;
  _x_type x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_type;
  _y_type y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::osm2rviz::Guide_line_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::osm2rviz::Guide_line_<ContainerAllocator> const> ConstPtr;

}; // struct Guide_line_

typedef ::osm2rviz::Guide_line_<std::allocator<void> > Guide_line;

typedef boost::shared_ptr< ::osm2rviz::Guide_line > Guide_linePtr;
typedef boost::shared_ptr< ::osm2rviz::Guide_line const> Guide_lineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::osm2rviz::Guide_line_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::osm2rviz::Guide_line_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::osm2rviz::Guide_line_<ContainerAllocator1> & lhs, const ::osm2rviz::Guide_line_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.heading == rhs.heading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::osm2rviz::Guide_line_<ContainerAllocator1> & lhs, const ::osm2rviz::Guide_line_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace osm2rviz

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::osm2rviz::Guide_line_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osm2rviz::Guide_line_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osm2rviz::Guide_line_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osm2rviz::Guide_line_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osm2rviz::Guide_line_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osm2rviz::Guide_line_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::osm2rviz::Guide_line_<ContainerAllocator> >
{
  static const char* value()
  {
    return "497c36b4f8b08b430204bff5826ad4da";
  }

  static const char* value(const ::osm2rviz::Guide_line_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x497c36b4f8b08b43ULL;
  static const uint64_t static_value2 = 0x0204bff5826ad4daULL;
};

template<class ContainerAllocator>
struct DataType< ::osm2rviz::Guide_line_<ContainerAllocator> >
{
  static const char* value()
  {
    return "osm2rviz/Guide_line";
  }

  static const char* value(const ::osm2rviz::Guide_line_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::osm2rviz::Guide_line_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] x\n"
"float32[] y\n"
"float32[] heading\n"
;
  }

  static const char* value(const ::osm2rviz::Guide_line_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::osm2rviz::Guide_line_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Guide_line_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::osm2rviz::Guide_line_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::osm2rviz::Guide_line_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "heading[]" << std::endl;
    for (size_t i = 0; i < v.heading.size(); ++i)
    {
      s << indent << "  heading[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.heading[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OSM2RVIZ_MESSAGE_GUIDE_LINE_H
